blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    path('<int:id>/', views.blog_detail, name='blog_detail'),
    path('create/', views.post_create, name='post_create'),
    path('<int:id>/edit/', views.post_edit, name='post_edit'),
]

carrito/urls.py
# carrito/urls.py
from django.urls import path
from . import views
from .views import agregar_al_carrito, quitar_del_carrito, ver_carrito,payment_view, success , create_payment_intent


app_name = 'carrito'

urlpatterns = [
    path('', views.ver_carrito, name='ver_carrito'),
    path('agregar/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('quitar/<int:item_id>/', views.quitar_del_carrito, name='quitar_del_carrito'),    
    path('payment/', payment_view, name='payment_view'),    
    path('create-payment-intent/', views.create_payment_intent, name='create_payment_intent'),
    path('success/', views.success, name='success'),

]

productos/urls.py
from django.urls import path
from . import views

app_name = 'productos'

urlpatterns = [
    path('', views.lista_productos, name='lista_productos'),
    path('<int:pk>/', views.producto_detalle, name='producto_detalle'),
    path('crear/', views.producto_crear, name='producto_crear'),
    path('<int:pk>/editar/', views.producto_editar, name='producto_editar'),
]

    
   

tienda_online/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('inicio.urls')),        # Incluye las URLs de la aplicación inicio
    path('', include('inicio.urls', namespace='inicio')),
    path('nosotros/', include('nosotros.urls')),  # Incluye las URLs de la aplicación nosotros
    path('contacto/', include('contacto.urls')),  # Incluye las URLs de la aplicación contacto
    
    path('blog/', include('blog.urls')),          # Incluye las URLs de la aplicación blog
    #path('experiencias/', include('experiencia.urls')), # Incluye las URLs de la aplicación experiencias
    #path('inventario/', include('inventario.urls')), # Incluye las URLs de la aplicación inventario
    #path('pagos/', include('pagos.urls')), # Incluye las URLs de la aplicación pagos
    #path('pedidos/', include('pedidos.urls')), # Incluye las URLs de la aplicación pedidos
    
    path('productos/', include('productos.urls', namespace='productos')), # Incluye las URLs de la aplicación productos
    path('usuarios/', include('usuarios.urls')), # Incluye las URLs de la aplicación usuarios
    path('carrito/', include('carrito.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # Agrega aquí las rutas de otras aplicaciones de tu proyecto

productos/models.py
# models.py
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=0)  # Cantidad en inventario
    imagen = models.ImageField(upload_to='productos/', blank=True, null=True)  # Campo de imagen
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

tienda_online/models.py
from django.db import models

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    categoria = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to='productos/', default='productos/default.jpg')

    destacado = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

class Pedido(models.Model):
    usuario = models.ForeignKey('Usuario', on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto)
    fecha_pedido = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=20)

    def __str__(self):
        return f'Pedido {self.id} - {self.estado}'

class Usuario(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    direccion = models.TextField()

    def __str__(self):
        return self.nombre

class Blog(models.Model):
    titulo = models.CharField(max_length=200)
    contenido = models.TextField()
    fecha_publicacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo

class Experiencia(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    experiencia = models.TextField()
    fecha_compartida = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Experiencia de {self.usuario.nombre}'

class Autorizacion(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    rol = models.CharField(max_length=50)
    permisos = models.TextField()

    def __str__(self):
        return f'Autorización de {self.usuario.nombre}'

class Inventario(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    ubicacion = models.CharField(max_length=100)

    def __str__(self):
        return f'Inventario de {self.producto.nombre}'

class Pago(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_pago = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Pago de {self.monto} para el pedido {self.pedido.id}'

productos/forms.py
# forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'descripcion', 'precio', 'stock', 'imagen', 'categoria']

productos/views.py
# views.py
from .forms import ProductoForm
from django.shortcuts import render, get_object_or_404, redirect
from .models import Producto, Categoria

def lista_productos(request):
    categoria_id = request.GET.get('categoria')
    if categoria_id:
        productos = Producto.objects.filter(categoria_id=categoria_id)
    else:
        productos = Producto.objects.all()

    categorias = Categoria.objects.all()
    
    return render(request, 'productos/lista_productos.html', {'productos': productos, 'categorias': categorias})

def producto_detalle(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    return render(request, 'productos/producto_detalle.html', {'producto': producto})

def producto_crear(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('lista_productos')
    else:
        form = ProductoForm()
    return render(request, 'productos/producto_form.html', {'form': form})

def producto_editar(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('lista_productos')
    else:
        form = ProductoForm(instance=producto)
    return render(request, 'productos/producto_form.html', {'form': form})

tienda_online/templates/productos/lista_productos.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="productos py-5">
    <div class="container">
        <div class="row mb-4">
            <div class="col-md-12">
                <h2>Todos los Productos</h2>
                <form method="get" class="form-inline">
                    <label for="categoria" class="mr-2">Filtrar por Categoría:</label>
                    <select name="categoria" id="categoria" class="form-control mr-2">
                        <option value="">Todas</option>
                        {% for categoria in categorias %}
                            <option value="{{ categoria.id }}" {% if request.GET.categoria == categoria.id|stringformat:"s" %}selected{% endif %}>
                                {{ categoria.nombre }}
                            </option>
                        {% endfor %}
                    </select>
                    <button type="submit" class="btn btn-primary">Filtrar</button>
                </form>
            </div>
        </div>
        <div class="row">
            {% for producto in productos %}
                <div class="col-md-4 mb-4">
                    <div class="card product-card h-100">
                        <img src="{{ producto.imagen.url }}" class="card-img-top product-img" alt="{{ producto.nombre }}">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">{{ producto.nombre }}</h5>
                            <p class="card-text">{{ producto.descripcion }}</p>
                            <p class="card-text"><strong>${{ producto.precio }}</strong></p>
                            <a href="{% url 'productos:producto_detalle' producto.id %}" class="btn btn-primary mt-auto">Ver Más</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

tienda_online/templates/productos/producto_detalle.html
<!-- templates/productos/producto_detalle.html -->
{% extends 'base.html' %}

{% block title %}{{ producto.nombre }}{% endblock %}

{% block content %}
<h2>{{ producto.nombre }}</h2>
<img src="{{ producto.imagen.url }}" class="img-fluid" alt="{{ producto.nombre }}">
<p>Descripción: {{ producto.descripcion }}</p>
<p>Precio: {{ producto.precio }}</p>
<p>Categoría: {{ producto.categoria.nombre }}</p>
<p>Stock disponible: {{ producto.stock }}</p>
<a href="{% url 'productos:lista_productos' %}">Volver a la lista</a>
<form action="{% url 'carrito:agregar_al_carrito' producto.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary mt-3">Agregar al carrito</button>
</form>
{% endblock %}

tienda_online/templates/productos/producto_form.html
<!-- productos/producto_form.html -->
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ form.instance.pk|yesno:"Editar Producto,Crear Producto" }}{% endblock %}

{% block content %}
<h1>{{ form.instance.pk|yesno:"Editar Producto,Crear Producto" }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock %}