blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    path('<int:id>/', views.blog_detail, name='blog_detail'),
    path('create/', views.post_create, name='post_create'),
    path('<int:id>/edit/', views.post_edit, name='post_edit'),
]

tienda_online/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('inicio.urls')),        # Incluye las URLs de la aplicación inicio
    path('', include('inicio.urls', namespace='inicio')),
    path('nosotros/', include('nosotros.urls')),  # Incluye las URLs de la aplicación nosotros
    path('contacto/', include('contacto.urls')),  # Incluye las URLs de la aplicación contacto
    
    path('blog/', include('blog.urls')),          # Incluye las URLs de la aplicación blog
    #path('experiencias/', include('experiencia.urls')), # Incluye las URLs de la aplicación experiencias
    #path('inventario/', include('inventario.urls')), # Incluye las URLs de la aplicación inventario
    #path('pagos/', include('pagos.urls')), # Incluye las URLs de la aplicación pagos
    #path('pedidos/', include('pedidos.urls')), # Incluye las URLs de la aplicación pedidos
    
    path('productos/', include('productos.urls', namespace='productos')), # Incluye las URLs de la aplicación productos
    path('usuarios/', include('usuarios.urls')), # Incluye las URLs de la aplicación usuarios
    path('carrito/', include('carrito.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # Agrega aquí las rutas de otras aplicaciones de tu proyecto

blog/models.py
# blog/models.py

from django.db import models
from django.utils.text import slugify

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='images/', blank=True, null=True)  # Añadir campo de imagen
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            original_slug = self.slug
            counter = 1
            while Post.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

tienda_online/models.py
from django.db import models

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    categoria = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to='productos/', default='productos/default.jpg')

    destacado = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

class Pedido(models.Model):
    usuario = models.ForeignKey('Usuario', on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto)
    fecha_pedido = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=20)

    def __str__(self):
        return f'Pedido {self.id} - {self.estado}'

class Usuario(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    direccion = models.TextField()

    def __str__(self):
        return self.nombre

class Blog(models.Model):
    titulo = models.CharField(max_length=200)
    contenido = models.TextField()
    fecha_publicacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo

class Experiencia(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    experiencia = models.TextField()
    fecha_compartida = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Experiencia de {self.usuario.nombre}'

class Autorizacion(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    rol = models.CharField(max_length=50)
    permisos = models.TextField()

    def __str__(self):
        return f'Autorización de {self.usuario.nombre}'

class Inventario(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    ubicacion = models.CharField(max_length=100)

    def __str__(self):
        return f'Inventario de {self.producto.nombre}'

class Pago(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_pago = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Pago de {self.monto} para el pedido {self.pedido.id}'

blog/forms.py
# blog/forms.py

from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']  # Incluye 'image' si está en el modelo
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 20}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }


"""from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }
"""

blog/views.py
from .models import Post
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm

def blog_index(request):
    posts = Post.objects.all()
    return render(request, 'blog/blog_index.html', {'posts': posts})

def blog_detail(request, id):
    post = get_object_or_404(Post, id=id)
    return render(request, 'blog/blog_detail.html', {'post': post})

def is_superuser(user):
    return user.is_superuser

@user_passes_test(is_superuser)
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('blog:blog_index')  # Asegúrate de que el nombre de la URL coincida
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {'form': form})

@user_passes_test(is_superuser)
def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:blog_index')  # Asegúrate de que el nombre de la URL coincida
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {'form': form})

tienda_online/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">{{ post.title }}</h1>
    {% if post.image %}
        <img src="{{ post.image.url }}" class="img-fluid mb-4" alt="{{ post.title }}">
    {% endif %}
    <p>{{ post.content }}</p>
    <a href="{% url 'blog:blog_index' %}" class="btn btn-secondary">Volver a la lista</a>
</div>
{% endblock %}

tienda_online/templates/blog/blog_index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Blog</h1>
    {% if user.is_superuser %}
        <a href="{% url 'blog:post_create' %}" class="btn btn-primary mb-4">Crear Nueva Publicación</a>
    {% endif %}
    <div class="row">
        {% for post in posts %}
            <div class="col-md-4 mb-4">
                <div class="blog-item">
                    {% if post.image %}
                        <img src="{{ post.image.url }}" class="img-fluid" alt="{{ post.title }}">
                    {% else %}
                        <img src="{% static 'images/default-blog-image.jpg' %}" class="img-fluid" alt="Default Image">
                    {% endif %}
                    <h5 class="mt-2">{{ post.title }}</h5>
                    <p>{{ post.content|slice:":200" }}...</p>
                    <a href="{% url 'blog:blog_detail' post.id %}" class="btn btn-primary">Leer Más</a>
                    {% if user.is_superuser %}
                        <a href="{% url 'blog:post_edit' post.id %}" class="btn btn-secondary">Editar</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

tienda_online/templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Crear/Editar Publicación</h1>
    <form method="post" enctype="multipart/form-data"> <!-- Asegúrate de incluir enctype -->
        {% csrf_token %}
        <div class="form-group">
            {{ form.title.label_tag }}
            {{ form.title }}
        </div>
        <div class="form-group">
            {{ form.content.label_tag }}
            {{ form.content }}
        </div>
        {% if form.image %}
        <div class="form-group">
            {{ form.image.label_tag }}
            {{ form.image }}
        </div>
        {% endif %}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
{% endblock %}