blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    path('<int:id>/', views.blog_detail, name='blog_detail'),
    path('create/', views.post_create, name='post_create'),
    path('<int:id>/edit/', views.post_edit, name='post_edit'),
]

carrito/urls.py
# carrito/urls.py
from django.urls import path
from . import views
from .views import agregar_al_carrito, quitar_del_carrito, ver_carrito,payment_view, success , create_payment_intent


app_name = 'carrito'

urlpatterns = [
    path('', views.ver_carrito, name='ver_carrito'),
    path('agregar/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('quitar/<int:item_id>/', views.quitar_del_carrito, name='quitar_del_carrito'),    
    path('payment/', payment_view, name='payment_view'),    
    path('create-payment-intent/', views.create_payment_intent, name='create_payment_intent'),
    path('success/', views.success, name='success'),

]

contacto/urls.py
# contacto/urls.py
from django.urls import path
from . import views

app_name = 'contacto'

urlpatterns = [
    path('', views.contacto, name='contacto'),
]

inicio/urls.py
from django.urls import path
from . import views

app_name = 'inicio'

urlpatterns = [
    path('', views.index, name='index'),
    path('producto/<int:id>/', views.producto_detalle, name='producto_detalle'),
]

nosotros/urls.py
from django.urls import path
from . import views

app_name = 'nosotros'

urlpatterns = [
    path('', views.about, name='about'),  # Ruta para la vista about de la aplicación nosotros
]

tienda_online/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('inicio.urls')),        # Incluye las URLs de la aplicación inicio
    path('', include('inicio.urls', namespace='inicio')),
    path('nosotros/', include('nosotros.urls')),  # Incluye las URLs de la aplicación nosotros
    path('contacto/', include('contacto.urls')),  # Incluye las URLs de la aplicación contacto
    
    path('blog/', include('blog.urls')),          # Incluye las URLs de la aplicación blog
    #path('experiencias/', include('experiencia.urls')), # Incluye las URLs de la aplicación experiencias
    #path('inventario/', include('inventario.urls')), # Incluye las URLs de la aplicación inventario
    #path('pagos/', include('pagos.urls')), # Incluye las URLs de la aplicación pagos
    #path('pedidos/', include('pedidos.urls')), # Incluye las URLs de la aplicación pedidos
    
    path('productos/', include('productos.urls', namespace='productos')), # Incluye las URLs de la aplicación productos
    path('usuarios/', include('usuarios.urls')), # Incluye las URLs de la aplicación usuarios
    path('carrito/', include('carrito.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # Agrega aquí las rutas de otras aplicaciones de tu proyecto

tienda_online/models.py
from django.db import models

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    categoria = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to='productos/', default='productos/default.jpg')

    destacado = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

class Pedido(models.Model):
    usuario = models.ForeignKey('Usuario', on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto)
    fecha_pedido = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=20)

    def __str__(self):
        return f'Pedido {self.id} - {self.estado}'

class Usuario(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    direccion = models.TextField()

    def __str__(self):
        return self.nombre

class Blog(models.Model):
    titulo = models.CharField(max_length=200)
    contenido = models.TextField()
    fecha_publicacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo

class Experiencia(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    experiencia = models.TextField()
    fecha_compartida = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Experiencia de {self.usuario.nombre}'

class Autorizacion(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    rol = models.CharField(max_length=50)
    permisos = models.TextField()

    def __str__(self):
        return f'Autorización de {self.usuario.nombre}'

class Inventario(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    ubicacion = models.CharField(max_length=100)

    def __str__(self):
        return f'Inventario de {self.producto.nombre}'

class Pago(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_pago = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Pago de {self.monto} para el pedido {self.pedido.id}'

tienda_online/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <title>{% block title %}Tienda Online{% endblock %}</title>
    {% load static %}

    <!-- Enlaces de CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">-->
</head>
<body>
    <header class="bg-light py-3 border-bottom">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center mb-3">
                <h1 class="page-title">DETALLES CON AMOR J&S</h1>
                <div class="button-container">
                    {% if user.is_authenticated %}
                        <a href="{% url 'usuarios:logout' %}" class="btn btn-custom btn-danger me-2">
                            <i class="fas fa-sign-out-alt"></i> Cerrar Sesión
                        </a>
                        <a href="{% url 'usuarios:profile' %}" class="btn btn-custom btn-primary me-2">
                            <i class="fas fa-user"></i> Mi Cuenta
                        </a>
                    {% else %}
                        <a href="{% url 'usuarios:login' %}" class="btn btn-custom btn-primary me-2">
                            <i class="fas fa-user"></i> Mi Cuenta
                        </a>
                    {% endif %}
                    <a href="{% url 'carrito:ver_carrito' %}" class="btn btn-custom btn-primary">
                        <i class="fas fa-shopping-cart"></i> Carrito
                    </a>
                </div>
            </div>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid px-0"> <!-- Utiliza container-fluid para un ancho completo -->
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'inicio:index' %}">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'productos:lista_productos' %}">Productos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:blog_index' %}">Blog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'nosotros:about' %}">Nosotros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'contacto:contacto' %}">Contacto</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            
        </div>
    </header>
    <main class="container my-4">
        {% block content %}
        <!-- Contenido específico de cada página -->
        {% endblock %}
    </main>
    <!-- Footer -->
<footer class="footer">
    <div class="container">
        <!-- Logo -->
        <div class="footer-logo">
            <img src="static\images\iconoTienda.png" alt="Logo" height="100">
        </div>
        
        <!-- Navigation Links -->
        <ul class="footer-nav">
            <li><a href="{% url 'inicio:index' %}">Inicio</a></li>
            <li><a href="{% url 'nosotros:about' %}">Nosotros</a></li>
            <li><a href="{% url 'productos:lista_productos' %}">Productos</a></li>
            <li><a href="{% url 'contacto:contacto' %}">Contacto</a></li>
        </ul>

        <!-- Social Media Icons -->
        <div class="footer-social">
            <a href="https://www.facebook.com/andresricardo.bateca" class="fab fa-facebook-f"></a>
            <a href="#" class="fab fa-twitter"></a>
            <a href="https://www.linkedin.com/in/andres-bateca-5301b3274/" class="fab fa-linkedin-in"></a>
            <a href="#" class="fab fa-instagram"></a>
        </div>
        
        <!-- Copyright -->
        <p>&copy; 2024 Detalles con amor J&S. Todos los derechos reservados.</p>
    </div>
</footer>


    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const alerts = document.querySelectorAll('.alert');
            alerts.forEach(alert => {
                alert.style.display = 'block';
                setTimeout(() => {
                    alert.style.display = 'none';
                }, 5000); // Mostrar mensaje durante 5 segundos
            });
        });
    </script>
</body>
</html>